"use client";
import {useState,useEffect,type ReactNode} from "react";
import {Plus,Save,ShieldCheck,FilePenLine,Check,BookOpen} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Textarea} from "@/components/ui/textarea";
import {Checkbox} from "@/components/ui/checkbox";
import {Select,SelectTrigger,SelectContent,SelectItem,SelectValue} from "@/components/ui/select";
import {Tabs,TabsList,TabsTrigger} from "@/components/ui/tabs";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {toast} from "sonner";
import type {Content,Kind,CaseStudy,Source} from "@/lib/civilist-types";
import {collection} from "@/lib/civilist-types";

const labels:Record<Kind,string>={branch:"Отрасли",lesson:"Уроки",card:"Карточки",question:"Задания",case:"Дела",practice:"Практика",document:"Документы"};
type Editable=Record<string,any>;
function Picker({value,onChange,items,label}:{value:string;onChange:(v:string)=>void;items:{id:string;title:string}[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue placeholder="Выбери"/></SelectTrigger><SelectContent>{items.map(x=><SelectItem key={x.id} value={x.id}>{x.title}</SelectItem>)}</SelectContent></Select>}
function Field({label,children}:{label:string;children:ReactNode}){return <div className="field"><span className="field-label">{label}</span>{children}</div>}
function today(){return new Date().toLocaleDateString("en-CA",{timeZone:"Europe/Moscow"})}
function blankSource():Source{return{label:"",url:"",checkedAt:today()}}
function blankNode(id:string,source:Source){return{id,scene:"",title:"",options:Array.from({length:4},(_,i)=>({text:"",feedback:"",correct:i===0})),source}}
function newMaterial(kind:Kind,c:Content):Editable{const id=kind+"-"+crypto.randomUUID();const common={id,title:""},source=blankSource(),branchId=c.branches[0]?.id||"",lessonId=c.lessons[0]?.id||"";switch(kind){case"branch":return{...common,description:"",group:"Частное право",icon:"BookOpen",color:"#08634e"};case"lesson":return{...common,branchId,topic:"",minutes:5,summary:"",points:[""],example:"",source};case"card":return{...common,branchId,lessonId,answer:"",source};case"question":return{...common,branchId,lessonId,type:"single",options:["","","",""],answer:[0],explanation:"",source};case"case":return{...common,branchId,summary:"",scenario:"",minutes:10,tags:[],paths:[{id:"client",label:"За клиента",start:"stage-1",nodes:[blankNode("stage-1",source)]}],success:"",failure:"",source};case"practice":return{...common,category:"Обзоры",date:today(),number:"",summary:"",decision:"",importance:"",norms:"",source};case"document":return{...common,category:"Досудебные",summary:"",checks:[""],risks:[""],body:"",source};}}

export default function AdminWorkbench({onReload}:{onReload:()=>Promise<void>}){
  const [content,setContent]=useState<Content|null>(null),[kind,setKind]=useState<Kind>("practice"),[mode,setMode]=useState("all"),[editing,setEditing]=useState<Editable|null>(null),[status,setStatus]=useState("draft"),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const load=async()=>{try{const r=await fetch("/api/admin",{cache:"no-store"}),a=await r.json() as {content:Content;error?:string};if(!r.ok)throw new Error(a.error);setContent(a.content);setError("");}catch(e){setError((e as Error).message)}};useEffect(()=>{void load()},[]);
  const save=async()=>{if(!editing)return;setBusy(true);try{const body=structuredClone(editing);delete body._status;if(kind==="case"){for(const p of body.paths){for(const n of p.nodes){if(!n.source.url)n.source=body.source;if(n.next==="end")delete n.next;}}}const r=await fetch("/api/admin",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind,status,body})});const data=await r.json() as {content:Content;error?:string};if(!r.ok)throw new Error(data.error);setEditing(null);await load();await onReload();toast.success(status==="published"?"Материал опубликован":"Черновик сохранён");}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}};
  const materials=content?(content[collection[kind]] as unknown as Editable[]).filter(m=>mode==="all"||m._status==="draft"):[];
  const drafts=content?Object.values(content).flat().filter((m:any)=>m._status==="draft").length:0;
  return <><div className="page-heading"><div><p className="eyebrow">АДМИНИСТРАТОР</p><h1>Библиотека материалов</h1><p>Добавляй учебный контент и проверяй подборки перед публикацией.</p></div><Button disabled={!content} onClick={()=>{setEditing(newMaterial(kind,content!));setStatus("draft")}}><Plus size={17}/> Добавить</Button></div><div className="note-strip editorial-note"><ShieldCheck size={23}/><p><strong>Сначала проверка, затем публикация.</strong> Недельные подборки появляются здесь как черновики. Открой материал, сверь полный текст и выбери «Опубликовать».</p><span className="badge">{drafts} черновиков</span></div><Tabs value={kind} onValueChange={v=>setKind(v as Kind)}><TabsList className="filter-tabs admin-tabs">{(Object.keys(labels) as Kind[]).map(k=><TabsTrigger value={k} key={k}>{labels[k]}</TabsTrigger>)}</TabsList></Tabs><div className="admin-toolbar"><Picker value={mode} onChange={setMode} label="Статус материалов" items={[{id:"all",title:"Все материалы"},{id:"draft",title:"Только черновики"}]}/><span className="meta">{materials.length} материалов</span></div>{error&&<div className="error-banner"><p>{error}</p><Button variant="outline" onClick={()=>void load()}>Повторить</Button></div>}<div className="admin-list">{materials.map(m=><article className="panel admin-row" key={m.id}><span className="icon-box"><BookOpen/></span><div><h3>{m.title}</h3><span className="meta">{m.source?.label||m.description}</span></div><span className={"badge "+(m._status==="draft"?"draft-badge":"")}>{m._status==="draft"?"Черновик":"Опубликовано"}</span><Button variant="outline" onClick={()=>{setEditing(structuredClone(m));setStatus(m._status||"draft")}}><FilePenLine size={16}/> Открыть</Button></article>)}</div>{content&&!materials.length&&<article className="panel empty"><h3>Материалов пока нет</h3><p>Добавь первый материал в выбранную категорию.</p></article>}<Dialog open={!!editing} onOpenChange={open=>{if(!open&&!busy)setEditing(null)}}><DialogContent className="material-editor"><DialogHeader><DialogTitle>{editing?.title||"Новый материал"}</DialogTitle><DialogDescription>{labels[kind]} · заполни содержание и проверь источник</DialogDescription></DialogHeader>{editing&&content&&<MaterialEditor kind={kind} value={editing} onChange={setEditing} content={content}/>}<div className="editor-save-row"><Picker label="Статус" value={status} onChange={setStatus} items={[{id:"draft",title:"Черновик"},{id:"published",title:"Опубликовано"}]}/><Button disabled={busy} onClick={()=>void save()}><Save size={17}/>{busy?"Сохраняем…":status==="published"?"Опубликовать":"Сохранить черновик"}</Button></div></DialogContent></Dialog></>;
}

function MaterialEditor({kind,value:v,onChange,content:c}:{kind:Kind;value:Editable;onChange:(v:Editable)=>void;content:Content}){
  const set=(k:string,value:unknown)=>onChange({...v,[k]:value});
  const text=(key:string,label:string,multi=false)=> <Field label={label}>{multi?<Textarea aria-label={label} rows={key==="body"?16:4} value={v[key]||""} onChange={e=>set(key,e.target.value)}/>:<Input aria-label={label} value={v[key]||""} onChange={e=>set(key,e.target.value)}/>}</Field>;
  const lines=(key:string,label:string)=> <Field label={label}><Textarea aria-label={label} rows={4} value={(v[key]||[]).join("\n")} onChange={e=>set(key,e.target.value.split("\n"))}/><small className="meta">Каждый пункт — с новой строки.</small></Field>;
  return <div className="editor-form">{text("title","Название")}{["lesson","card","question","case"].includes(kind)&&<Field label="Отрасль"><Picker value={v.branchId} onChange={x=>set("branchId",x)} items={c.branches} label="Отрасль"/></Field>}{["card","question"].includes(kind)&&<Field label="Связанный урок"><Picker value={v.lessonId} onChange={x=>onChange({...v,lessonId:x,branchId:c.lessons.find(l=>l.id===x)?.branchId||v.branchId})} items={c.lessons} label="Урок"/></Field>}
    {kind==="branch"&&<>{text("description","Описание")}{text("group","Группа направлений")}<Field label="Цвет"><Input aria-label="Цвет направления" type="color" value={v.color} onChange={e=>set("color",e.target.value)}/></Field></>}
    {kind==="lesson"&&<>{text("topic","Тема")}<Field label="Продолжительность, минут"><Input type="number" min={1} max={180} value={v.minutes} onChange={e=>set("minutes",Number(e.target.value))}/></Field>{text("summary","Главное",true)}{lines("points","Что запомнить")}{text("example","Практический пример",true)}</>}
    {kind==="card"&&text("answer","Ответ",true)}
    {kind==="question"&&<><Field label="Тип задания"><Picker value={v.type} onChange={type=>onChange({...v,type,answer:type==="single"?[0]:[],left:type==="matching"?(v.left||["","","",""]):v.left})} label="Тип задания" items={[{id:"single",title:"Один ответ"},{id:"multiple",title:"Несколько ответов"},{id:"matching",title:"Соответствие"},{id:"sequence",title:"Последовательность"},{id:"short",title:"Письменный ответ"}]}/></Field>{v.type==="short"?text("model","Эталон для самопроверки",true):<>{lines("options",v.type==="matching"?"Определения справа":"Варианты ответа")}{v.type==="matching"&&lines("left","Понятия слева")}<Field label={v.type==="sequence"?"Правильная последовательность":v.type==="matching"?"Правильные соответствия":"Правильный ответ"}>{v.type==="multiple"?<div className="editor-choices">{v.options.map((o:string,i:number)=><label key={i}><Checkbox checked={v.answer.includes(i)} onCheckedChange={yes=>set("answer",yes?[...v.answer,i]:v.answer.filter((x:number)=>x!==i))}/>{o||`Вариант ${i+1}`}</label>)}</div>:v.type==="single"?<Picker value={String(v.answer[0]??0)} label="Правильный ответ" items={v.options.map((o:string,i:number)=>({id:String(i),title:o||`Вариант ${i+1}`}))} onChange={x=>set("answer",[Number(x)])}/>:<div className="editor-choices">{v.options.map((_:string,i:number)=><Field key={i} label={v.type==="matching"?v.left?.[i]||`Понятие ${i+1}`:`Позиция ${i+1}`}><Picker value={v.answer[i]===undefined?"":String(v.answer[i])} label={`Правильная позиция ${i+1}`} items={v.options.map((o:string,j:number)=>({id:String(j),title:o||`Вариант ${j+1}`}))} onChange={x=>{const answer=[...v.answer];answer[i]=Number(x);set("answer",answer)}}/></Field>)}</div>}</Field></>}{text("explanation","Объяснение ответа",true)}</>}
    {kind==="practice"&&<><Field label="Категория"><Picker value={v.category} onChange={x=>set("category",x)} items={["Обзоры","Пленумы","Дела"].map(x=>({id:x,title:x}))} label="Категория практики"/></Field><Field label="Дата документа"><Input type="date" value={v.date} onChange={e=>set("date",e.target.value)} aria-label="Дата документа"/></Field>{text("number","Номер и наименование акта")}{text("summary","Суть",true)}{text("decision","Основной вывод",true)}{text("importance","Почему важно",true)}{text("norms","Нормы для исследования",true)}</>}
    {kind==="document"&&<>{text("category","Категория")}{text("summary","Когда применяется",true)}{lines("checks","Перед использованием проверить")}{text("body","Текст с полями [УКАЗАТЬ]",true)}{lines("risks","Что учесть при адаптации")}</>}
    {kind==="case"&&<>{text("summary","Краткая завязка",true)}{text("scenario","Обстоятельства дела",true)}{lines("tags","Ключевые темы")}<CaseEditor value={v as CaseStudy} onChange={onChange}/>{text("success","Итог при обоснованной позиции",true)}{text("failure","Итог при ошибках",true)}</>}
    {v.source&&<div className="editor-source"><h3>Источник и проверка</h3><Field label="Норма или документ"><Input value={v.source.label} aria-label="Наименование источника" onChange={e=>set("source",{...v.source,label:e.target.value})}/></Field><Field label="Ссылка на полный текст"><Input type="url" placeholder="https://…" aria-label="Ссылка на источник" value={v.source.url} onChange={e=>set("source",{...v.source,url:e.target.value})}/></Field><Field label="Дата проверки"><Input type="date" aria-label="Дата проверки источника" value={v.source.checkedAt} max={today()} onChange={e=>set("source",{...v.source,checkedAt:e.target.value})}/></Field></div>}
  </div>;
}
function CaseEditor({value:v,onChange}:{value:CaseStudy;onChange:(v:Editable)=>void}){
  const [role,setRole]=useState(v.paths[0]?.id||"");const pi=Math.max(0,v.paths.findIndex(p=>p.id===role)),path=v.paths[pi];
  const alter=(edit:(clone:CaseStudy)=>void)=>{const clone=structuredClone(v);edit(clone);onChange(clone)};
  const items=[{id:"end",title:"Завершить дело"},...path.nodes.map(n=>({id:n.id,title:n.title||"Новый этап"}))];
  return <div className="case-editor"><h3>Стороны и этапы</h3><Picker value={path.id} onChange={setRole} items={v.paths.map(p=>({id:p.id,title:p.label}))} label="Сторона дела"/><Field label="Название стороны"><Input value={path.label} onChange={e=>alter(c=>{c.paths[pi].label=e.target.value})}/></Field><Field label="Первый этап"><Picker value={path.start} label="Первый этап" items={items.filter(i=>i.id!=="end")} onChange={x=>alter(c=>{c.paths[pi].start=x})}/></Field>{path.nodes.map((n,ni)=><details key={n.id} className="stage-editor"><summary>{ni+1}. {n.title||"Новый этап"}</summary><Field label="Сцена"><Textarea value={n.scene} aria-label="Описание сцены" onChange={e=>alter(c=>{c.paths[pi].nodes[ni].scene=e.target.value})}/></Field><Field label="Вопрос"><Input value={n.title} aria-label="Вопрос этапа" onChange={e=>alter(c=>{c.paths[pi].nodes[ni].title=e.target.value})}/></Field><Field label="Следующий этап по умолчанию"><Picker value={n.next||"end"} label="Следующий этап" items={items.filter(i=>i.id!==n.id)} onChange={x=>alter(c=>{if(x==="end")delete c.paths[pi].nodes[ni].next;else c.paths[pi].nodes[ni].next=x})}/></Field>{n.options.map((o,oi)=><div className="case-choice-edit" key={oi}><Field label={`Вариант ${"АБВГДЕ"[oi]}`}><Input value={o.text} aria-label={`Вариант ${oi+1}`} onChange={e=>alter(c=>{c.paths[pi].nodes[ni].options[oi].text=e.target.value})}/></Field><Field label="Объяснение"><Textarea value={o.feedback} rows={2} aria-label="Объяснение выбора" onChange={e=>alter(c=>{c.paths[pi].nodes[ni].options[oi].feedback=e.target.value})}/></Field><label className="checkbox-label"><Checkbox checked={o.correct} onCheckedChange={yes=>alter(c=>{c.paths[pi].nodes[ni].options[oi].correct=!!yes})}/> Обоснованный выбор</label><Field label="Переход после этого выбора"><Picker value={o.next||"default"} label="Переход выбора" items={[{id:"default",title:"Как по умолчанию"},...items.filter(i=>i.id!==n.id)]} onChange={x=>alter(c=>{if(x==="default")delete c.paths[pi].nodes[ni].options[oi].next;else c.paths[pi].nodes[ni].options[oi].next=x})}/></Field></div>)}</details>)}<div className="button-row"><Button variant="outline" onClick={()=>alter(c=>{const p=c.paths[pi],id="stage-"+crypto.randomUUID();if(p.nodes.length)p.nodes[p.nodes.length-1].next=id;p.nodes.push(blankNode(id,c.source))})}><Plus size={16}/> Добавить этап</Button>{v.paths.length<3&&<Button variant="outline" onClick={()=>{const id="side-"+crypto.randomUUID();alter(c=>{c.paths.push({id,label:"Новая сторона",start:"stage-1",nodes:[blankNode("stage-1",c.source)]})});setRole(id)}}>Добавить сторону</Button>}</div></div>;
}
