import {useEffect,useState} from 'react';
import type {Content,Question,State} from '@/lib/civilist-types';
import type {Answer,AssessmentResult,Mode} from '@/lib/assessment';
import {validAnswer} from '@/lib/assessment';
import {Button} from '@/components/ui/button';
import {Progress} from '@/components/ui/progress';
import QuestionInput from './QuestionInput';
type Attempt={id:string;mode:Mode;branchId:string;target:string;title:string;status:string;questions:Question[];answers:Record<string,Answer>;result:AssessmentResult|null;passPercent:number;state?:State};
export default function AssessmentView({mode,target,content,onState,onDone}:{mode:Mode;target:string;content:Content;onState:(s:State)=>void;onDone:(branch:string,section:string)=>void}){
 const [attempt,setAttempt]=useState<Attempt|null>(null),[answers,setAnswers]=useState<Record<string,Answer>>({}),[index,setIndex]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const lesson=content.lessons.find(l=>l.id===target);
 let branchId=lesson?.branchId||'',section=lesson?.topic||'';
 if(mode==='section'){try{const pair=JSON.parse(target);if(Array.isArray(pair)&&pair.length===2&&pair.every(x=>typeof x==='string'))[branchId,section]=pair;}catch{}}
 const call=async(body:unknown):Promise<Attempt>=>{const r=await fetch('/api/assessment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json() as Attempt&{error?:string};if(!r.ok)throw new Error(data.error||'Не удалось сохранить.');return data;};
 const begin=async(resume=false)=>{setBusy(true);setError('');try{const savedId=resume?new URLSearchParams(window.location.search).get('attempt'):null;
 let a:Attempt;if(savedId){const r=await fetch('/api/assessment?id='+encodeURIComponent(savedId));const data=await r.json() as Attempt&{error?:string};if(!r.ok)throw new Error(data.error||'Попытка недоступна.');if(data.mode!==mode||data.branchId!==branchId||data.target!==(mode==='topic'?target:section))throw new Error('Попытка относится к другой теме.');a=data;}else a=await call({action:'start',mode,branchId,target:mode==='topic'?target:section});
 const url=new URL(window.location.href);url.searchParams.set('attempt',a.id);window.history.replaceState({},'',url);setAttempt(a);setAnswers(a.answers);setIndex(Math.max(0,a.questions.findIndex(q=>!validAnswer(q,a.answers[q.id]))));}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 useEffect(()=>{void begin(true);},[]);
 const save=async(next?:number,finish=false)=>{if(!attempt||busy)return;setBusy(true);setError('');try{const a=await call({action:finish?'finish':'save',id:attempt.id,answers});setAttempt(a);if(a.state)onState(a.state);if(next!==undefined)setIndex(next);}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const leave=async()=>{if(!attempt||attempt.status==='finished'){onDone(branchId,section);return;}setBusy(true);setError('');try{await call({action:'save',id:attempt.id,answers});onDone(branchId,section);}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const q=attempt?.questions[index],value=q?answers[q.id]:undefined;
 const complete=attempt?.questions.filter(q=>validAnswer(q,answers[q.id])).length||0;
 return <div className="training-surface"><Button variant="ghost" disabled={busy} onClick={()=>void leave()}>Сохранить и к оглавлению</Button>
  <div className="page-heading"><div><p className="eyebrow">{mode==='section'?'ИТОГОВЫЙ ТЕСТ РАЗДЕЛА':'ТЕСТ ТЕМЫ'}</p><h1>{attempt?.title||lesson?.title||section}</h1><p>Зачёт — от {attempt?.passPercent||80}% проверяемых ответов. Разбор появится после отправки всех ответов.</p></div></div>
  {error&&<div role="alert" className="panel"><p>{error}</p>{!attempt&&<Button onClick={()=>void begin()} disabled={busy}>Повторить загрузку</Button>}</div>}
  {!attempt&&!error&&<p role="status">Готовим задания…</p>}
  {attempt?.result?<article className="panel assessment-result"><h2>{attempt.result.passed?'Тест сдан':'Нужно повторить материал'}</h2><p>{attempt.result.score} из {attempt.result.total} · {attempt.result.percent}%</p>{attempt.result.written>0&&<p>Письменных ответов для самопроверки: {attempt.result.written}. Они не включены в оценку.</p>}
   {attempt.questions.map((q,i)=>{const f=attempt.result!.feedback.find(f=>f.id===q.id)!;const a=attempt.answers[q.id];const display=(v:Answer)=>typeof v==='string'?v:q.type==='matching'?q.left?.map((l,i)=>`${l} — ${q.options[v[i]]}`).join('; '):v.map(n=>q.options[n]).join(q.type==='sequence'?' → ':'; ');return <details key={q.id} open={f.correct===false} className="assessment-review"><summary>{i+1}. {f.correct===null?'Самопроверка':f.correct?'Верно':'Ошибка'}: {q.title}</summary><p><strong>Твой ответ: </strong>{display(a)}</p><p><strong>{f.model?'Эталон: ':'Правильный ответ: '}</strong>{f.model||display(f.answer)}</p><p>{f.explanation}</p><p className="meta">{f.norms}</p><Button variant="ghost" onClick={()=>onDone(q.branchId,content.lessons.find(l=>l.id===q.lessonId)?.topic||section)}>К разделу темы</Button></details>;})}
   <div className="button-row"><Button onClick={()=>void begin()} disabled={busy}>Новая попытка</Button><Button variant="outline" onClick={()=>onDone(branchId,section)}>К оглавлению</Button></div>
  </article>:q&&attempt&&<><p className="session-progress">Задание {index+1} из {attempt.questions.length} · заполнено {complete}</p><Progress value={complete/attempt.questions.length*100}/><article className="panel quiz-panel"><h2>{q.title}</h2><QuestionInput q={q} selected={Array.isArray(value)?value:[]} setSelected={v=>setAnswers(a=>({...a,[q.id]:v}))} text={typeof value==='string'?value:''} setText={v=>setAnswers(a=>({...a,[q.id]:v}))} disabled={busy}/><div className="button-row"><Button variant="outline" disabled={busy||index===0} onClick={()=>void save(index-1)}>Предыдущее</Button>{index<attempt.questions.length-1?<Button disabled={busy||!validAnswer(q,value)} onClick={()=>void save(index+1)}>Сохранить и дальше</Button>:<Button disabled={busy||complete!==attempt.questions.length} onClick={()=>void save(undefined,true)}>Завершить тест</Button>}</div><p className="meta">Ответ сохраняется при переходе между заданиями или нажатии «Сохранить и к оглавлению».</p></article><nav className="assessment-navigation" aria-label="Задания теста">{attempt.questions.map((q,i)=><Button key={q.id} aria-label={`Задание ${i+1}${validAnswer(q,answers[q.id])?', заполнено':''}`} aria-current={index===i?'step':undefined} variant={index===i?'default':'outline'} disabled={busy} onClick={()=>void save(i)}>{i+1}{validAnswer(q,answers[q.id])?' ✓':''}</Button>)}</nav></>}
 </div>;
}
