import type {Question} from '@/lib/civilist-types';
import {Textarea} from '@/components/ui/textarea';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Button} from '@/components/ui/button';
import {Checkbox} from '@/components/ui/checkbox';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
export default function QuestionInput({q,selected,setSelected,text,setText,disabled}:{q:Question;selected:number[];setSelected:(v:number[])=>void;text:string;setText:(v:string)=>void;disabled:boolean}){
  if(q.type==="short")return <Textarea aria-label="Твой письменный ответ" value={text} onChange={e=>setText(e.target.value)} placeholder="Сформулируй ответ своими словами…" rows={6} disabled={disabled}/>;
  if(q.type==="matching")return <div className="matching-list">{q.left?.map((left,i)=><div key={left}><span>{left}</span><Select value={selected[i]===undefined||selected[i]<0?"":String(selected[i])} disabled={disabled} onValueChange={v=>{const next=Array.from({length:q.options.length},(_,j)=>selected[j]??-1);next[i]=Number(v);setSelected(next)}}><SelectTrigger aria-label={`Определение для ${left}`}><SelectValue placeholder="Выбери определение"/></SelectTrigger><SelectContent>{q.options.map((o,j)=><SelectItem key={j} value={String(j)} disabled={selected.some((v,k)=>v===j&&k!==i)}>{o}</SelectItem>)}</SelectContent></Select></div>)}</div>;
  if(q.type==="sequence")return <div><p className="instruction">Нажимай на этапы в правильном порядке. Нажатие на выбранный этап убирает его.</p><div className="sequence-selected">{selected.map((v,i)=><button key={v} disabled={disabled} onClick={()=>setSelected(selected.filter(x=>x!==v))}><span>{i+1}</span>{q.options[v]}<span className="remove">×</span></button>)}</div><div className="sequence-options">{q.options.map((o,i)=><Button variant="outline" disabled={disabled||selected.includes(i)} key={o} onClick={()=>setSelected([...selected,i])}>{o}</Button>)}</div></div>;
  if(q.type==="multiple")return <div className="answer-options">{q.options.map((o,i)=><label className={"answer-option "+(selected.includes(i)?"selected":"")} key={o}><Checkbox checked={selected.includes(i)} disabled={disabled} onCheckedChange={v=>setSelected(v?[...selected,i]:selected.filter(x=>x!==i))}/><span className="option-letter">{"АБВГДЕ"[i]}</span><span>{o}</span></label>)}</div>;
  return <RadioGroup value={selected.length?String(selected[0]):""} onValueChange={v=>setSelected([Number(v)])} disabled={disabled} className="answer-options">{q.options.map((o,i)=><label className={"answer-option "+(selected[0]===i?"selected":"")} key={o}><RadioGroupItem value={String(i)} id={q.id+"-"+i}/><span className="option-letter">{"АБВГДЕ"[i]}</span><span>{o}</span></label>)}</RadioGroup>;
}
