import {getChatGPTUser} from "@/app/chatgpt-auth";
import {config,db,ensureSeed} from "@/lib/civilist-db";
import {schemas} from "@/lib/content-validation";
import {z} from "zod";
export const dynamic="force-dynamic";
// Service calls enter only through private Sites dispatch. This endpoint can write drafts only.
async function permitted(){const user=await getChatGPTUser();if(user)return !!config("CIVILIST_ADMIN_EMAIL")&&user.email.toLowerCase()===config("CIVILIST_ADMIN_EMAIL").toLowerCase();return config("CIVILIST_PRIVATE_EDITORIAL_WRITER")==="enabled";}
export async function GET(){if(!await permitted())return Response.json({error:"Нет доступа"},{status:403});try{await ensureSeed();const rows=await db().prepare("SELECT body,status FROM content WHERE kind = 'practice' ORDER BY updated_at DESC").all<{body:string;status:string}>();return Response.json({materials:rows.results.map(r=>({id:JSON.parse(r.body).id,title:JSON.parse(r.body).title,url:JSON.parse(r.body).source.url,status:r.status}))},{headers:{"Cache-Control":"no-store"}});}catch{return Response.json({error:"Подборки временно недоступны."},{status:503});}}
export async function POST(request:Request){if(!await permitted())return Response.json({error:"Нет доступа"},{status:403});if(request.headers.get("origin")&&request.headers.get("origin")!==new URL(request.url).origin)return Response.json({error:"Недопустимый запрос"},{status:403});try{const a=z.object({entries:z.array(schemas.practice).max(8)}).parse(await request.json());await ensureSeed();const saved:string[]=[],skipped:string[]=[];for(const entry of a.entries){const found=await db().prepare("SELECT id FROM content WHERE kind = 'practice' AND (id = ? OR json_extract(body,'$.source.url') = ?) LIMIT 1").bind(entry.id,entry.source.url).first();if(found){skipped.push(entry.id);continue;}await db().prepare("INSERT OR IGNORE INTO content (id,kind,body,status,updated_at) VALUES (?,?,?,?,?)").bind(entry.id,"practice",JSON.stringify(entry),"draft",new Date().toISOString()).run();saved.push(entry.id);}return Response.json({saved,skipped,published:false});}catch(e){console.error("editorial write failed",e);return Response.json({error:e instanceof z.ZodError?e.issues.map(i=>i.message).join("; "):"Не удалось сохранить подборку."},{status:400});}}
